language: objective-c
osx_image: xcode8.3
xcode_workspace: dslrbrowser.xcworkspace
xcode_scheme: dslrbrowserTests
script:
  - pod install
  - xcodebuild clean -sdk iphoneos10.3 -target dslrbrowser CODE_SIGNING_REQUIRED=NO


